# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Takumi < Formula
  desc "AI-aware, language-agnostic workspace builder"
  homepage "https://github.com/T-Fizz/takumi"
  version "1.0.2"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/T-Fizz/takumi/releases/download/v1.0.2/takumi_1.0.2_darwin_amd64.tar.gz"
      sha256 "7dcf7f2a5389caaadcf36d5b22349fdb28c20841ec0429dd6ce81651649fbcec"

      define_method(:install) do
        bin.install "takumi"
        bin.install_symlink bin/"takumi" => "t"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/T-Fizz/takumi/releases/download/v1.0.2/takumi_1.0.2_darwin_arm64.tar.gz"
      sha256 "23325f610e7af6ccecfcd06468f20b0f919544e422f1d761d80f2a0e74b8b834"

      define_method(:install) do
        bin.install "takumi"
        bin.install_symlink bin/"takumi" => "t"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/T-Fizz/takumi/releases/download/v1.0.2/takumi_1.0.2_linux_amd64.tar.gz"
      sha256 "f0ee6d5b5fd8ef2ebe0961cf8ff53fe20ab57d94201f1931b1560bd202945c25"
      define_method(:install) do
        bin.install "takumi"
        bin.install_symlink bin/"takumi" => "t"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/T-Fizz/takumi/releases/download/v1.0.2/takumi_1.0.2_linux_arm64.tar.gz"
      sha256 "4e628cf5784b170625075898765d5ea5626c3cd0bd54f9759f5611a2ab6e46a2"
      define_method(:install) do
        bin.install "takumi"
        bin.install_symlink bin/"takumi" => "t"
      end
    end
  end

  test do
    assert_match "takumi", shell_output("#{bin}/takumi --help")
  end
end
