# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Takumi < Formula
  desc "AI-aware, language-agnostic workspace builder"
  homepage "https://github.com/T-Fizz/takumi"
  version "1.0.1"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/T-Fizz/takumi/releases/download/v1.0.1/takumi_1.0.1_darwin_amd64.tar.gz"
      sha256 "6eb7bc5d97dc1cf69ba0c5d482edce0bdd472b3b29f32c63041633e5a20452d6"

      define_method(:install) do
        bin.install "takumi"
        bin.install_symlink bin/"takumi" => "t"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/T-Fizz/takumi/releases/download/v1.0.1/takumi_1.0.1_darwin_arm64.tar.gz"
      sha256 "81bf1b1a7846c26a44c166c98694475407813a73c0394c41255113fd1c087b64"

      define_method(:install) do
        bin.install "takumi"
        bin.install_symlink bin/"takumi" => "t"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/T-Fizz/takumi/releases/download/v1.0.1/takumi_1.0.1_linux_amd64.tar.gz"
      sha256 "3e3e364b11ba759b29aaa64bc742247de637098c3ff972ac3103b83a015c1e1c"
      define_method(:install) do
        bin.install "takumi"
        bin.install_symlink bin/"takumi" => "t"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/T-Fizz/takumi/releases/download/v1.0.1/takumi_1.0.1_linux_arm64.tar.gz"
      sha256 "719440b75c2480479fbba307e663e637ef41ef82049f159664dcf2c02395368d"
      define_method(:install) do
        bin.install "takumi"
        bin.install_symlink bin/"takumi" => "t"
      end
    end
  end

  test do
    assert_match "takumi", shell_output("#{bin}/takumi --help")
  end
end
