# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Takumi < Formula
  desc "AI-aware, language-agnostic workspace builder"
  homepage "https://github.com/T-Fizz/takumi"
  version "1.0.2"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/T-Fizz/takumi/releases/download/v1.0.2/takumi_1.0.2_darwin_amd64.tar.gz"
      sha256 "5e25abcec8d9fb1075ecd76e507c830200595e586b8ce2b52dc60cb063ab2eed"

      define_method(:install) do
        bin.install "takumi"
        bin.install_symlink bin/"takumi" => "t"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/T-Fizz/takumi/releases/download/v1.0.2/takumi_1.0.2_darwin_arm64.tar.gz"
      sha256 "3c89a2a0ffd4e81e8466740f35affb633e8f338364403eb50f11c046e10c9e40"

      define_method(:install) do
        bin.install "takumi"
        bin.install_symlink bin/"takumi" => "t"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/T-Fizz/takumi/releases/download/v1.0.2/takumi_1.0.2_linux_amd64.tar.gz"
      sha256 "a23cc34fb32b98acf15d7bc39c81f185fc095c479e04f69ccfa184f572541ef3"
      define_method(:install) do
        bin.install "takumi"
        bin.install_symlink bin/"takumi" => "t"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/T-Fizz/takumi/releases/download/v1.0.2/takumi_1.0.2_linux_arm64.tar.gz"
      sha256 "03832e59578e7945768033946bba67412a0ef6f29b45c3de39e1a5dfc57d52c6"
      define_method(:install) do
        bin.install "takumi"
        bin.install_symlink bin/"takumi" => "t"
      end
    end
  end

  test do
    assert_match "takumi", shell_output("#{bin}/takumi --help")
  end
end
